### ISSUE TITLE
Crucible 1.1

### ISSUE THREAD

**Issue by ozatomic** [stschake/blue_patcher#1]
You were not on IRC at this time so i thought this might be easyier to let you know as i dont know how to debug this yet.

[+] writing backup
[+] success: blue.dll.bak
[+] finding pattern in binary...
[+] 0% processed
[+] 10% processed
[+] 20% processed
[+] 30% processed
[+] 40% processed
[+] 50% processed
[+] 60% processed
[+] 70% processed
[+] 80% processed
[+] 90% processed
[+] 100% processed
[+] 100% processed
[+] failure: pattern not found!

**Comment by stschake** [comment]
Fixed 7d529c530f90a357dc753d8bd4b5915b9addd2ab
